import { normalizarTexto } from './texto'

export type IdentidadeNBACurada = {
  alias: string
  personId: number | null
  nomeOficial: string | null
}

/**
 * Catálogo curado de apresentação, derivado dos personIds e nomes oficiais
 * já conferidos em demo/fotos.ts em 07/09/2026. Fonte: NBA.com/players.
 * Não é reconciliação automática: um alias só vale para um UUID quando o
 * vínculo editorial foi confirmado. Wiggins permanece explicitamente ambíguo.
 * Time do provedor e time editorial não são alterados por este catálogo.
 */
export const FONTE_IDENTIDADES_NBA = {
  url: 'https://www.nba.com/players',
  verificadoEm: '2026-09-07',
  origem: 'Curadoria de personIds e comentários de demo/fotos.ts',
} as const

export const IDENTIDADES_NBA: readonly IdentidadeNBACurada[] = [
  { alias: 'Brunson', personId: 1628973, nomeOficial: 'Jalen Brunson' },
  { alias: 'Towns', personId: 1626157, nomeOficial: 'Karl-Anthony Towns' },
  { alias: 'Anunoby', personId: 1628384, nomeOficial: 'OG Anunoby' },
  { alias: 'Bridges', personId: 1628969, nomeOficial: 'Mikal Bridges' },
  { alias: 'hart', personId: 1628404, nomeOficial: 'Josh Hart' },
  { alias: 'Shamet', personId: 1629013, nomeOficial: 'Landry Shamet' },
  { alias: 'Mc bride', personId: 1630540, nomeOficial: 'Miles McBride' },
  { alias: 'Drumond', personId: 203083, nomeOficial: 'Andre Drummond' },
  { alias: 'Wembayama', personId: 1641705, nomeOficial: 'Victor Wembanyama' },
  { alias: 'Castle', personId: 1642264, nomeOficial: 'Stephon Castle' },
  { alias: 'Fox', personId: 1628368, nomeOficial: "De'Aaron Fox" },
  { alias: 'Tobias Harris', personId: 202699, nomeOficial: 'Tobias Harris' },
  { alias: 'Vassel', personId: 1630170, nomeOficial: 'Devin Vassell' },
  { alias: 'Harper', personId: 1642844, nomeOficial: 'Dylan Harper' },
  { alias: 'champagnie', personId: 1630577, nomeOficial: 'Julian Champagnie' },
  { alias: 'Kornet', personId: 1628436, nomeOficial: 'Luke Kornet' },
  { alias: 'Kelton Jhonson', personId: 1629640, nomeOficial: 'Keldon Johnson' },
  { alias: 'Shai', personId: 1628983, nomeOficial: 'Shai Gilgeous-Alexander' },
  { alias: 'Jallem Williams', personId: 1631114, nomeOficial: 'Jalen Williams' },
  { alias: 'Chet holmgreen', personId: 1631096, nomeOficial: 'Chet Holmgren' },
  { alias: 'Ajay Mitchell', personId: 1642349, nomeOficial: 'Ajay Mitchell' },
  { alias: 'Mcain', personId: 1642272, nomeOficial: 'Jared McCain' },
  { alias: 'Isaiah Harteinein', personId: 1628392, nomeOficial: 'Isaiah Hartenstein' },
  { alias: 'Cason Wallace', personId: 1641717, nomeOficial: 'Cason Wallace' },
  { alias: 'Jaylim Williams', personId: 1631119, nomeOficial: 'Jaylin Williams' },
  { alias: 'Caruso', personId: 1627936, nomeOficial: 'Alex Caruso' },
  { alias: 'Donovan Mitchel', personId: 1628378, nomeOficial: 'Donovan Mitchell' },
  { alias: 'James Harden', personId: 201935, nomeOficial: 'James Harden' },
  { alias: 'Evan Mobley', personId: 1630596, nomeOficial: 'Evan Mobley' },
  { alias: 'Jarret Allen', personId: 1628386, nomeOficial: 'Jarrett Allen' },
  { alias: 'Tyson', personId: 1642281, nomeOficial: 'Jaylon Tyson' },
  { alias: 'Sam Merrill', personId: 1630241, nomeOficial: 'Sam Merrill' },
  { alias: 'Max strus', personId: 1629622, nomeOficial: 'Max Strus' },
  { alias: 'Cade Cunningham', personId: 1630595, nomeOficial: 'Cade Cunningham' },
  { alias: 'Jalen Duren', personId: 1631105, nomeOficial: 'Jalen Duren' },
  { alias: 'Collins', personId: 1628381, nomeOficial: 'John Collins' },
  { alias: 'Duncan Robinson', personId: 1629130, nomeOficial: 'Duncan Robinson' },
  { alias: 'Isaiah Joe', personId: 1630198, nomeOficial: 'Isaiah Joe' },
  { alias: 'jenkins', personId: 1642450, nomeOficial: 'Daniss Jenkins' },
  { alias: 'Huerter', personId: 1628989, nomeOficial: 'Kevin Huerter' },
  { alias: 'Ausar Thompson', personId: 1641709, nomeOficial: 'Ausar Thompson' },
  { alias: 'Jokic', personId: 203999, nomeOficial: 'Nikola Jokić' },
  { alias: 'Jamal Murray', personId: 1627750, nomeOficial: 'Jamal Murray' },
  { alias: 'Gordon', personId: 203932, nomeOficial: 'Aaron Gordon' },
  { alias: 'Cameron Jhonson', personId: 1629661, nomeOficial: 'Cameron Johnson' },
  { alias: 'Braun', personId: 1631128, nomeOficial: 'Christian Braun' },
  { alias: 'Peyton Watson', personId: 1631212, nomeOficial: 'Peyton Watson' },
  { alias: 'Derozan', personId: 201942, nomeOficial: 'DeMar DeRozan' },
  { alias: 'Kuminga', personId: 1630228, nomeOficial: 'Jonathan Kuminga' },
  { alias: 'Bagley 2', personId: 1628963, nomeOficial: 'Marvin Bagley III' },
  { alias: 'Strahwther', personId: 1631124, nomeOficial: 'Julian Strawther' },
  { alias: 'Anthony Edward', personId: 1630162, nomeOficial: 'Anthony Edwards' },
  { alias: 'Lamello Ball', personId: 1630163, nomeOficial: 'LaMelo Ball' },
  { alias: 'Dosunmu', personId: 1630245, nomeOficial: 'Ayo Dosunmu' },
  { alias: 'McDaniels', personId: 1630183, nomeOficial: 'Jaden McDaniels' },
  { alias: 'Gobert', personId: 203497, nomeOficial: 'Rudy Gobert' },
  { alias: 'Hyland', personId: 1630538, nomeOficial: 'Bones Hyland' },
  { alias: 'Shannon', personId: 1630545, nomeOficial: 'Terrence Shannon Jr' },
  { alias: 'Luka Doncic', personId: 1629029, nomeOficial: 'Luka Dončić' },
  { alias: 'Austin Reaves', personId: 1630559, nomeOficial: 'Austin Reaves' },
  { alias: 'Grimes', personId: 1629656, nomeOficial: 'Quentin Grimes' },
  { alias: 'Kesller', personId: 1631117, nomeOficial: 'Walker Kessler' },
  { alias: 'Mamukelashivili', personId: 1630572, nomeOficial: 'Sandro Mamukelashvili' },
  { alias: 'Sexton', personId: 1629012, nomeOficial: 'Collin Sexton' },
  { alias: 'Laravia', personId: 1631222, nomeOficial: 'Jake LaRavia' },
  { alias: 'Embid', personId: 203954, nomeOficial: 'Joel Embiid' },
  { alias: 'Jaylen Brown', personId: 1627759, nomeOficial: 'Jaylen Brown' },
  { alias: 'Maxey', personId: 1630178, nomeOficial: 'Tyrese Maxey' },
  { alias: 'LeBron James', personId: 2544, nomeOficial: 'LeBron James' },
  { alias: 'Edjecombe', personId: 1642845, nomeOficial: 'VJ Edgecombe' },
  { alias: 'Simmons', personId: 1629014, nomeOficial: 'Anfernee Simons' },
  { alias: 'Barlow', personId: 1631230, nomeOficial: 'Dominick Barlow' },
  { alias: 'Devin Booker', personId: 1626164, nomeOficial: 'Devin Booker' },
  { alias: 'Jalen green', personId: 1630224, nomeOficial: 'Jalen Green' },
  { alias: 'Brooks', personId: 1628415, nomeOficial: 'Dillon Brooks' },
  { alias: 'Miles Bridges', personId: 1628970, nomeOficial: 'Miles Bridges' },
  { alias: 'Gillespie', personId: 1631221, nomeOficial: 'Collin Gillespie' },
  { alias: 'Mark Williams', personId: 1631109, nomeOficial: 'Mark Williams' },
  { alias: 'Luke Lenard', personId: 1628379, nomeOficial: 'Luke Kennard' },
  { alias: 'Brendon miller', personId: 1641706, nomeOficial: 'Brandon Miller' },
  { alias: 'Knueppel', personId: 1642851, nomeOficial: 'Kon Knueppel' },
  { alias: 'Coby white', personId: 1629632, nomeOficial: 'Coby White' },
  { alias: 'Naz Reid', personId: 1629675, nomeOficial: 'Naz Reid' },
  { alias: 'grasson Allen', personId: 1628960, nomeOficial: 'Grayson Allen' },
  { alias: 'Diabate', personId: 1631217, nomeOficial: 'Moussa Diabaté' },
  { alias: 'Irving', personId: 202681, nomeOficial: 'Kyrie Irving' },
  { alias: 'Cooper Fllag', personId: 1642843, nomeOficial: 'Cooper Flagg' },
  { alias: 'PJ washinton', personId: 1629023, nomeOficial: 'P.J. Washington' },
  { alias: 'Max cristie', personId: 1631108, nomeOficial: 'Max Christie' },
  { alias: 'Marshall', personId: 1630230, nomeOficial: 'Naji Marshall' },
  { alias: 'Aldama', personId: 1630583, nomeOficial: 'Santi Aldama' },
  { alias: 'Klay Thompson', personId: 202691, nomeOficial: 'Klay Thompson' },
  { alias: 'Gafford', personId: 1629655, nomeOficial: 'Daniel Gafford' },
  { alias: 'Risacher', personId: 1642258, nomeOficial: 'Zaccharie Risacher' },
  { alias: 'stephen Curry', personId: 201939, nomeOficial: 'Stephen Curry' },
  { alias: 'Butler', personId: 202710, nomeOficial: 'Jimmy Butler III' },
  { alias: 'Porzigins', personId: 204001, nomeOficial: 'Kristaps Porziņģis' },
  { alias: 'podzienki', personId: 1641764, nomeOficial: 'Brandin Podziemski' },
  { alias: 'Gui Santos', personId: 1630611, nomeOficial: 'Gui Santos' },
  { alias: 'Green', personId: 203110, nomeOficial: 'Draymond Green' },
  { alias: 'Kawhi Leonard', personId: 202695, nomeOficial: 'Kawhi Leonard' },
  { alias: 'Barnes', personId: 1630567, nomeOficial: 'Scottie Barnes' },
  { alias: 'Barret', personId: 1629628, nomeOficial: 'RJ Barrett' },
  { alias: 'Quirkleyy', personId: 1630193, nomeOficial: 'Immanuel Quickley' },
  { alias: 'Potl', personId: 1627751, nomeOficial: 'Jakob Poeltl' },
  { alias: 'Murray Boyles', personId: 1642867, nomeOficial: 'Collin Murray-Boyles' },
  { alias: 'Jamal Shead', personId: 1642347, nomeOficial: 'Jamal Shead' },
  { alias: 'Tatum', personId: 1628369, nomeOficial: 'Jayson Tatum' },
  { alias: 'Pritchard', personId: 1630202, nomeOficial: 'Payton Pritchard' },
  { alias: 'Paul George', personId: 202331, nomeOficial: 'Paul George' },
  { alias: 'Derick White', personId: 1628401, nomeOficial: 'Derrick White' },
  { alias: 'Queta', personId: 1629674, nomeOficial: 'Neemias Queta' },
  { alias: 'Hauser', personId: 1630573, nomeOficial: 'Sam Hauser' },
  { alias: 'Garza', personId: 1630568, nomeOficial: 'Luka Garza' },
  { alias: 'Kevin Durant', personId: 201142, nomeOficial: 'Kevin Durant' },
  { alias: 'sengun', personId: 1630578, nomeOficial: 'Alperen Sengun' },
  { alias: 'Amem Thompson', personId: 1641708, nomeOficial: 'Amen Thompson' },
  { alias: 'Jabari smith', personId: 1631095, nomeOficial: 'Jabari Smith Jr.' },
  { alias: 'Sheepard', personId: 1642263, nomeOficial: 'Reed Sheppard' },
  { alias: 'Van fleet', personId: 1627832, nomeOficial: 'Fred VanVleet' },
  { alias: 'Eason', personId: 1631106, nomeOficial: 'Tari Eason' },
  { alias: 'Smart', personId: 203935, nomeOficial: 'Marcus Smart' },
  { alias: 'Banchero', personId: 1631094, nomeOficial: 'Paolo Banchero' },
  { alias: 'Franz Wagner', personId: 1630532, nomeOficial: 'Franz Wagner' },
  { alias: 'Bane', personId: 1630217, nomeOficial: 'Desmond Bane' },
  { alias: 'Suggs', personId: 1630591, nomeOficial: 'Jalen Suggs' },
  { alias: 'Anthony black', personId: 1641710, nomeOficial: 'Anthony Black' },
  { alias: 'Vucevic', personId: 202696, nomeOficial: 'Nikola Vučević' },
  { alias: 'Carter Jr', personId: 1628976, nomeOficial: 'Wendell Carter Jr.' },
  { alias: 'Tristan da Silva', personId: 1641783, nomeOficial: 'Tristan da Silva' },
  { alias: 'Lillard', personId: 203081, nomeOficial: 'Damian Lillard' },
  { alias: 'Avdija', personId: 1630166, nomeOficial: 'Deni Avdija' },
  { alias: 'Já morant', personId: 1629630, nomeOficial: 'Ja Morant' },
  { alias: 'holiday', personId: 201950, nomeOficial: 'Jrue Holiday' },
  { alias: 'Sharpe', personId: 1631101, nomeOficial: 'Shaedon Sharpe' },
  { alias: 'Henderson', personId: 1630703, nomeOficial: 'Scoot Henderson' },
  { alias: 'Camara', personId: 1641739, nomeOficial: 'Toumani Camara' },
  { alias: 'Clingan', personId: 1642270, nomeOficial: 'Donovan Clingan' },
  { alias: 'Giannis', personId: 203507, nomeOficial: 'Giannis Antetokounmpo' },
  { alias: 'Adebayo', personId: 1628389, nomeOficial: 'Bam Adebayo' },
  { alias: 'Wiggins', personId: null, nomeOficial: null },
  { alias: 'Hardaway JR', personId: 203501, nomeOficial: 'Tim Hardaway Jr.' },
  { alias: 'Larsson', personId: 1641796, nomeOficial: 'Pelle Larsson' },
  { alias: 'Davion Mitchell', personId: 1630558, nomeOficial: 'Davion Mitchell' },
  { alias: 'Portis', personId: 1626171, nomeOficial: 'Bobby Portis Jr.' },
  { alias: 'Fontenchhio', personId: 1631323, nomeOficial: 'Simone Fontecchio' },
  { alias: 'Lauri', personId: 1628374, nomeOficial: 'Lauri Markkanen' },
  { alias: 'Keyonte', personId: 1641718, nomeOficial: 'Keyonte George' },
  { alias: 'Jaren Jackson Jr', personId: 1628991, nomeOficial: 'Jaren Jackson Jr.' },
  { alias: 'Ace Bailey', personId: 1642846, nomeOficial: 'Ace Bailey' },
  { alias: 'sensabaugh', personId: 1641729, nomeOficial: 'Brice Sensabaugh' },
  { alias: 'Nurkic', personId: 203994, nomeOficial: 'Jusuf Nurkić' },
  { alias: 'Zion', personId: 1629627, nomeOficial: 'Zion Williamson' },
  { alias: 'Trey Murphy', personId: 1630530, nomeOficial: 'Trey Murphy III' },
  { alias: 'dejount Murray', personId: 1627749, nomeOficial: 'Dejounte Murray' },
  { alias: 'Sadiq Bey', personId: 1630180, nomeOficial: 'Saddiq Bey' },
  { alias: 'Jordan Poole', personId: 1629673, nomeOficial: 'Jordan Poole' },
  { alias: 'Jeremiah ferrs', personId: 1642847, nomeOficial: 'Jeremiah Fears' },
  { alias: 'Derik Queen', personId: 1642852, nomeOficial: 'Derik Queen' },
  { alias: 'Herbert Jones', personId: 1630529, nomeOficial: 'Herbert Jones' },
  { alias: 'Powel', personId: 1626181, nomeOficial: 'Norman Powell' },
  { alias: 'Giddey', personId: 1630581, nomeOficial: 'Josh Giddey' },
  { alias: 'Buzzelis', personId: 1641824, nomeOficial: 'Matas Buzelis' },
  { alias: 'tre Jone', personId: 1630200, nomeOficial: 'Tre Jones' },
  { alias: 'Claxton', personId: 1629651, nomeOficial: 'Nic Claxton' },
  { alias: 'Okoro', personId: 1630171, nomeOficial: 'Isaac Okoro' },
  { alias: 'Cale Wilson', personId: 1643410, nomeOficial: 'Caleb Wilson' },
  { alias: 'Jalen Johnson', personId: 1630552, nomeOficial: 'Jalen Johnson' },
  { alias: 'Nickeil Alexander Walker', personId: 1629638, nomeOficial: 'Nickeil Alexander-Walker' },
  { alias: 'CJ McCollum', personId: 203468, nomeOficial: 'CJ McCollum' },
  { alias: 'okonguwu', personId: 1630168, nomeOficial: 'Onyeka Okongwu' },
  { alias: 'Daniels', personId: 1630700, nomeOficial: 'Dyson Daniels' },
  { alias: 'kispert', personId: 1630557, nomeOficial: 'Corey Kispert' },
  { alias: 'Landale', personId: 1629111, nomeOficial: 'Jock Landale' },
  { alias: 'Dort', personId: 1629652, nomeOficial: 'Luguentz Dort' },
  { alias: 'Ingram', personId: 1627742, nomeOficial: 'Brandon Ingram' },
  { alias: 'Garland', personId: 1629636, nomeOficial: 'Darius Garland' },
  { alias: 'Mathurin', personId: 1631097, nomeOficial: 'Bennedict Mathurin' },
  { alias: 'Hachimura', personId: 1629060, nomeOficial: 'Rui Hachimura' },
  { alias: 'Derick Jone Jr', personId: 1627884, nomeOficial: 'Derrick Jones Jr.' },
  { alias: 'J. Miller', personId: 1641757, nomeOficial: 'Jordan Miller' },
  { alias: 'Brook Lopez', personId: 201572, nomeOficial: 'Brook Lopez' },
  { alias: 'Dick', personId: 1641711, nomeOficial: 'Gradey Dick' },
  { alias: 'Lavine', personId: 203897, nomeOficial: 'Zach LaVine' },
  { alias: 'Sabonis', personId: 1627734, nomeOficial: 'Domantas Sabonis' },
  { alias: 'Hunter', personId: 1629631, nomeOficial: "De'Andre Hunter" },
  { alias: 'king Murray', personId: 1631099, nomeOficial: 'Keegan Murray' },
  { alias: 'malik monk', personId: 1628370, nomeOficial: 'Malik Monk' },
  { alias: 'Clifford', personId: 1642363, nomeOficial: 'Nique Clifford' },
  { alias: 'Achiuwa', personId: 1630173, nomeOficial: 'Precious Achiuwa' },
  { alias: 'Reynard', personId: 1642875, nomeOficial: 'Maxime Raynaud' },
  { alias: 'Ty Jerome', personId: 1629660, nomeOficial: 'Ty Jerome' },
  { alias: 'Grant', personId: 203924, nomeOficial: 'Jerami Grant' },
  { alias: 'Coward', personId: 1642907, nomeOficial: 'Cedric Coward' },
  { alias: 'Zach Edey', personId: 1641744, nomeOficial: 'Zach Edey' },
  { alias: 'wells', personId: 1642377, nomeOficial: 'Jaylen Wells' },
  { alias: 'pippen jr', personId: 1630590, nomeOficial: 'Scotty Pippen Jr.' },
  { alias: 'Cam Spencer', personId: 1642285, nomeOficial: 'Cam Spencer' },
  { alias: 'GG Jackson', personId: 1641713, nomeOficial: 'GG Jackson' },
  { alias: 'Siakam', personId: 1627783, nomeOficial: 'Pascal Siakam' },
  { alias: 'Haliburton', personId: 1630169, nomeOficial: 'Tyrese Haliburton' },
  { alias: 'Nembhard', personId: 1629614, nomeOficial: 'Andrew Nembhard' },
  { alias: 'zubac', personId: 1627826, nomeOficial: 'Ivica Zubac' },
  { alias: 'Nesmith', personId: 1630174, nomeOficial: 'Aaron Nesmith' },
  { alias: 'Kelly oubre', personId: 1626162, nomeOficial: 'Kelly Oubre Jr.' },
  { alias: 'Toppin', personId: 1630167, nomeOficial: 'Obi Toppin' },
  { alias: 'Jerace walker', personId: 1641716, nomeOficial: 'Jarace Walker' },
  { alias: 'McConnell', personId: 204456, nomeOficial: 'T.J. McConnell' },
  { alias: 'Michael porter Jr', personId: 1629008, nomeOficial: 'Michael Porter Jr.' },
  { alias: 'Julius randlle', personId: 203944, nomeOficial: 'Julius Randle' },
  { alias: 'Clonley', personId: 1641730, nomeOficial: 'Noah Clowney' },
  { alias: 'ego demim', personId: 1642856, nomeOficial: 'Egor Dëmin' },
  { alias: 'M wagner', personId: 1629021, nomeOficial: 'Moritz Wagner' },
  { alias: 'Dany Wolf', personId: 1642874, nomeOficial: 'Danny Wolf' },
  { alias: 'Keon Ellis', personId: 1631165, nomeOficial: 'Keon Ellis' },
  { alias: 'Anthony Davies', personId: 203076, nomeOficial: 'Anthony Davis' },
  { alias: 'Trae young', personId: 1629027, nomeOficial: 'Trae Young' },
  { alias: 'Alexandre SArr', personId: 1642259, nomeOficial: 'Alex Sarr' },
  { alias: 'kyshwan George', personId: 1642273, nomeOficial: 'Kyshawn George' },
  { alias: 'Ayton', personId: 1629028, nomeOficial: 'Deandre Ayton' },
  { alias: 'TRE Johnson', personId: 1642848, nomeOficial: 'Tre Johnson' },
  { alias: 'carrington', personId: 1642267, nomeOficial: 'Bub Carrington' },
  { alias: 'Dybantsa', personId: 1643407, nomeOficial: 'AJ Dybantsa' },
  { alias: 'Tyler Herro', personId: 1629639, nomeOficial: 'Tyler Herro' },
  { alias: 'Kevin porter', personId: 1629645, nomeOficial: 'Kevin Porter Jr.' },
  { alias: 'Rollins', personId: 1631157, nomeOficial: 'Ryan Rollins' },
  { alias: 'jasquez jr', personId: 1631170, nomeOficial: 'Jaime Jaquez Jr.' },
  { alias: 'Kuzma', personId: 1628398, nomeOficial: 'Kyle Kuzma' },
  { alias: 'Turner', personId: 1626167, nomeOficial: 'Myles Turner' },
  { alias: 'Ware', personId: 1642276, nomeOficial: "Kel'el Ware" },
  { alias: 'Dieng', personId: 1631172, nomeOficial: 'Ousmane Dieng' },
]

const porAlias = new Map(IDENTIDADES_NBA.map((i) => [normalizarTexto(i.alias), i]))
const porPersonId = new Map(
  IDENTIDADES_NBA.filter((i) => i.personId !== null).map((i) => [i.personId, i]),
)

export function identidadeNbaPorAlias(alias: string): IdentidadeNBACurada | undefined {
  return porAlias.get(normalizarTexto(alias))
}

export function identidadeNbaPorPersonId(personId: number): IdentidadeNBACurada | undefined {
  return porPersonId.get(personId)
}
