-- DESCIDA de 0000_glamorous_absorbing_man.sql — GERADO por scripts/gerar-down.mjs, não editar à mão.

DROP INDEX IF EXISTS "sessoes_usuario_idx";
DROP INDEX IF EXISTS "apitos_feed_idx";
DROP INDEX IF EXISTS "niveis_versao_unica_ativa";
DROP INDEX IF EXISTS "lesoes_escalacao_jogo_status_idx";
DROP INDEX IF EXISTS "jogos_data_idx";
DROP INDEX IF EXISTS "estatisticas_quarto_1q_idx";
DROP INDEX IF EXISTS "estatisticas_jogo_jogador_idx";
ALTER TABLE "sessoes" DROP CONSTRAINT IF EXISTS "sessoes_dispositivo_id_dispositivos_id_fk";
ALTER TABLE "sessoes" DROP CONSTRAINT IF EXISTS "sessoes_usuario_id_usuarios_id_fk";
ALTER TABLE "push_inscricoes" DROP CONSTRAINT IF EXISTS "push_inscricoes_dispositivo_id_dispositivos_id_fk";
ALTER TABLE "push_inscricoes" DROP CONSTRAINT IF EXISTS "push_inscricoes_usuario_id_usuarios_id_fk";
ALTER TABLE "preferencias_notificacao" DROP CONSTRAINT IF EXISTS "preferencias_notificacao_usuario_id_usuarios_id_fk";
ALTER TABLE "dispositivos" DROP CONSTRAINT IF EXISTS "dispositivos_usuario_id_usuarios_id_fk";
ALTER TABLE "assinaturas" DROP CONSTRAINT IF EXISTS "assinaturas_usuario_id_usuarios_id_fk";
ALTER TABLE "apitos" DROP CONSTRAINT IF EXISTS "apitos_jogador_id_jogadores_id_fk";
ALTER TABLE "apitos" DROP CONSTRAINT IF EXISTS "apitos_jogo_id_jogos_id_fk";
ALTER TABLE "odds_snapshot" DROP CONSTRAINT IF EXISTS "odds_snapshot_jogador_id_jogadores_id_fk";
ALTER TABLE "odds_snapshot" DROP CONSTRAINT IF EXISTS "odds_snapshot_jogo_id_jogos_id_fk";
ALTER TABLE "odds_snapshot" DROP CONSTRAINT IF EXISTS "odds_snapshot_casa_id_casas_id_fk";
ALTER TABLE "odds_agregada" DROP CONSTRAINT IF EXISTS "odds_agregada_jogador_id_jogadores_id_fk";
ALTER TABLE "odds_agregada" DROP CONSTRAINT IF EXISTS "odds_agregada_jogo_id_jogos_id_fk";
ALTER TABLE "mapa_mercados" DROP CONSTRAINT IF EXISTS "mapa_mercados_casa_id_casas_id_fk";
ALTER TABLE "niveis" DROP CONSTRAINT IF EXISTS "niveis_time_id_times_id_fk";
ALTER TABLE "niveis" DROP CONSTRAINT IF EXISTS "niveis_jogador_id_jogadores_id_fk";
ALTER TABLE "niveis" DROP CONSTRAINT IF EXISTS "niveis_niveis_versao_id_niveis_versao_id_fk";
ALTER TABLE "medias_jogador" DROP CONSTRAINT IF EXISTS "medias_jogador_jogador_id_jogadores_id_fk";
ALTER TABLE "mapa_jogadores" DROP CONSTRAINT IF EXISTS "mapa_jogadores_jogador_id_jogadores_id_fk";
ALTER TABLE "lesoes_escalacao" DROP CONSTRAINT IF EXISTS "lesoes_escalacao_jogador_id_jogadores_id_fk";
ALTER TABLE "lesoes_escalacao" DROP CONSTRAINT IF EXISTS "lesoes_escalacao_jogo_id_jogos_id_fk";
ALTER TABLE "jogos" DROP CONSTRAINT IF EXISTS "jogos_time_visitante_id_times_id_fk";
ALTER TABLE "jogos" DROP CONSTRAINT IF EXISTS "jogos_time_casa_id_times_id_fk";
ALTER TABLE "jogadores" DROP CONSTRAINT IF EXISTS "jogadores_time_id_times_id_fk";
ALTER TABLE "estatisticas_time_jogo" DROP CONSTRAINT IF EXISTS "estatisticas_time_jogo_time_id_times_id_fk";
ALTER TABLE "estatisticas_time_jogo" DROP CONSTRAINT IF EXISTS "estatisticas_time_jogo_jogo_id_jogos_id_fk";
ALTER TABLE "estatisticas_quarto" DROP CONSTRAINT IF EXISTS "estatisticas_quarto_jogador_id_jogadores_id_fk";
ALTER TABLE "estatisticas_quarto" DROP CONSTRAINT IF EXISTS "estatisticas_quarto_jogo_id_jogos_id_fk";
ALTER TABLE "estatisticas_jogo" DROP CONSTRAINT IF EXISTS "estatisticas_jogo_jogador_id_jogadores_id_fk";
ALTER TABLE "estatisticas_jogo" DROP CONSTRAINT IF EXISTS "estatisticas_jogo_jogo_id_jogos_id_fk";
ALTER TABLE "classificacao" DROP CONSTRAINT IF EXISTS "classificacao_time_id_times_id_fk";
DROP TABLE IF EXISTS "saude_provedor" CASCADE;
DROP TABLE IF EXISTS "log_falhas" CASCADE;
DROP TABLE IF EXISTS "usuarios" CASCADE;
DROP TABLE IF EXISTS "sessoes" CASCADE;
DROP TABLE IF EXISTS "push_inscricoes" CASCADE;
DROP TABLE IF EXISTS "preferencias_notificacao" CASCADE;
DROP TABLE IF EXISTS "dispositivos" CASCADE;
DROP TABLE IF EXISTS "assinaturas" CASCADE;
DROP TABLE IF EXISTS "rulesets" CASCADE;
DROP TABLE IF EXISTS "feed_snapshot" CASCADE;
DROP TABLE IF EXISTS "apitos" CASCADE;
DROP TABLE IF EXISTS "odds_snapshot" CASCADE;
DROP TABLE IF EXISTS "odds_agregada" CASCADE;
DROP TABLE IF EXISTS "mapa_mercados" CASCADE;
DROP TABLE IF EXISTS "casas" CASCADE;
DROP TABLE IF EXISTS "niveis_versao" CASCADE;
DROP TABLE IF EXISTS "niveis" CASCADE;
DROP TABLE IF EXISTS "times" CASCADE;
DROP TABLE IF EXISTS "medias_jogador" CASCADE;
DROP TABLE IF EXISTS "mapa_jogadores" CASCADE;
DROP TABLE IF EXISTS "lesoes_escalacao" CASCADE;
DROP TABLE IF EXISTS "jogos" CASCADE;
DROP TABLE IF EXISTS "jogadores" CASCADE;
DROP TABLE IF EXISTS "estatisticas_time_jogo" CASCADE;
DROP TABLE IF EXISTS "estatisticas_quarto" CASCADE;
DROP TABLE IF EXISTS "estatisticas_jogo" CASCADE;
DROP TABLE IF EXISTS "classificacao" CASCADE;
DROP TYPE IF EXISTS "public"."tipo_provedor" CASCADE;
DROP TYPE IF EXISTS "public"."tipo_dispositivo" CASCADE;
DROP TYPE IF EXISTS "public"."status_usuario" CASCADE;
DROP TYPE IF EXISTS "public"."status_ruleset" CASCADE;
DROP TYPE IF EXISTS "public"."status_jogo" CASCADE;
DROP TYPE IF EXISTS "public"."status_escalacao" CASCADE;
DROP TYPE IF EXISTS "public"."severidade" CASCADE;
DROP TYPE IF EXISTS "public"."origem_odds" CASCADE;
DROP TYPE IF EXISTS "public"."nivel_jogador" CASCADE;
DROP TYPE IF EXISTS "public"."metodo" CASCADE;
DROP TYPE IF EXISTS "public"."janela_media" CASCADE;
DROP TYPE IF EXISTS "public"."estrategia" CASCADE;
DROP TYPE IF EXISTS "public"."canal_notificacao" CASCADE;
DROP TYPE IF EXISTS "public"."atributo" CASCADE;
