-- DESCIDA de 0019_demonic_silver_surfer.sql — GERADO por scripts/gerar-down.mjs, não editar à mão.

DROP INDEX IF EXISTS "liberacoes_repasses_comissao_idx";
DROP INDEX IF EXISTS "itens_importacao_parceiro_idx";
DROP INDEX IF EXISTS "eventos_afiliados_atribuicao_idx";
DROP INDEX IF EXISTS "eventos_afiliados_link_data_idx";
DROP INDEX IF EXISTS "convites_afiliados_email_idx";
DROP INDEX IF EXISTS "comissoes_afiliados_parceiro_idx";
DROP INDEX IF EXISTS "auditoria_afiliados_entidade_idx";
DROP INDEX IF EXISTS "atribuicoes_afiliados_usuario_idx";
DROP INDEX IF EXISTS "atribuicoes_afiliados_visitante_idx";
DROP INDEX IF EXISTS "alocacoes_repasses_liberacao_idx";
DROP INDEX IF EXISTS "acordos_afiliados_vigencia_idx";
ALTER TABLE "repasses_afiliados" DROP CONSTRAINT IF EXISTS "repasses_afiliados_registrado_por_id_usuarios_id_fk";
ALTER TABLE "repasses_afiliados" DROP CONSTRAINT IF EXISTS "repasses_afiliados_parceiro_id_parceiros_afiliados_id_fk";
ALTER TABLE "recebimentos_casas" DROP CONSTRAINT IF EXISTS "recebimentos_casas_registrado_por_id_usuarios_id_fk";
ALTER TABLE "recebimentos_casas" DROP CONSTRAINT IF EXISTS "recebimentos_casas_casa_id_casas_id_fk";
ALTER TABLE "parceiros_afiliados" DROP CONSTRAINT IF EXISTS "parceiros_afiliados_usuario_id_usuarios_id_fk";
ALTER TABLE "ofertas_afiliados" DROP CONSTRAINT IF EXISTS "ofertas_afiliados_casa_id_casas_id_fk";
ALTER TABLE "lotes_importacao_afiliados" DROP CONSTRAINT IF EXISTS "lotes_importacao_afiliados_confirmado_por_id_usuarios_id_fk";
ALTER TABLE "lotes_importacao_afiliados" DROP CONSTRAINT IF EXISTS "lotes_importacao_afiliados_importado_por_id_usuarios_id_fk";
ALTER TABLE "lotes_importacao_afiliados" DROP CONSTRAINT IF EXISTS "lotes_importacao_afiliados_oferta_id_ofertas_afiliados_id_fk";
ALTER TABLE "lotes_importacao_afiliados" DROP CONSTRAINT IF EXISTS "lotes_importacao_afiliados_casa_id_casas_id_fk";
ALTER TABLE "links_afiliados" DROP CONSTRAINT IF EXISTS "links_afiliados_campanha_id_campanhas_afiliados_id_fk";
ALTER TABLE "liberacoes_repasses" DROP CONSTRAINT IF EXISTS "liberacoes_repasses_liberado_por_id_usuarios_id_fk";
ALTER TABLE "liberacoes_repasses" DROP CONSTRAINT IF EXISTS "liberacoes_repasses_comissao_id_comissoes_afiliados_id_fk";
ALTER TABLE "itens_importacao_afiliados" DROP CONSTRAINT IF EXISTS "itens_importacao_afiliados_link_id_links_afiliados_id_fk";
ALTER TABLE "itens_importacao_afiliados" DROP CONSTRAINT IF EXISTS "itens_importacao_afiliados_campanha_id_campanhas_afiliados_id_fk";
ALTER TABLE "itens_importacao_afiliados" DROP CONSTRAINT IF EXISTS "itens_importacao_afiliados_parceiro_id_parceiros_afiliados_id_fk";
ALTER TABLE "itens_importacao_afiliados" DROP CONSTRAINT IF EXISTS "itens_importacao_afiliados_oferta_id_ofertas_afiliados_id_fk";
ALTER TABLE "itens_importacao_afiliados" DROP CONSTRAINT IF EXISTS "itens_importacao_afiliados_casa_id_casas_id_fk";
ALTER TABLE "itens_importacao_afiliados" DROP CONSTRAINT IF EXISTS "itens_importacao_afiliados_lote_id_lotes_importacao_afiliados_id_fk";
ALTER TABLE "eventos_afiliados" DROP CONSTRAINT IF EXISTS "eventos_afiliados_atribuicao_id_atribuicoes_afiliados_id_fk";
ALTER TABLE "eventos_afiliados" DROP CONSTRAINT IF EXISTS "eventos_afiliados_link_id_links_afiliados_id_fk";
ALTER TABLE "eventos_afiliados" DROP CONSTRAINT IF EXISTS "eventos_afiliados_usuario_id_usuarios_id_fk";
ALTER TABLE "convites_afiliados" DROP CONSTRAINT IF EXISTS "convites_afiliados_parceiro_id_parceiros_afiliados_id_fk";
ALTER TABLE "convites_afiliados" DROP CONSTRAINT IF EXISTS "convites_afiliados_criado_por_id_usuarios_id_fk";
ALTER TABLE "comissoes_afiliados" DROP CONSTRAINT IF EXISTS "comissoes_afiliados_acordo_id_acordos_afiliados_id_fk";
ALTER TABLE "comissoes_afiliados" DROP CONSTRAINT IF EXISTS "comissoes_afiliados_parceiro_id_parceiros_afiliados_id_fk";
ALTER TABLE "comissoes_afiliados" DROP CONSTRAINT IF EXISTS "comissoes_afiliados_item_importacao_id_itens_importacao_afiliados_id_fk";
ALTER TABLE "campanhas_afiliados" DROP CONSTRAINT IF EXISTS "campanhas_afiliados_criado_por_id_usuarios_id_fk";
ALTER TABLE "campanhas_afiliados" DROP CONSTRAINT IF EXISTS "campanhas_afiliados_oferta_id_ofertas_afiliados_id_fk";
ALTER TABLE "campanhas_afiliados" DROP CONSTRAINT IF EXISTS "campanhas_afiliados_parceiro_id_parceiros_afiliados_id_fk";
ALTER TABLE "auditoria_afiliados" DROP CONSTRAINT IF EXISTS "auditoria_afiliados_ator_usuario_id_usuarios_id_fk";
ALTER TABLE "atribuicoes_afiliados" DROP CONSTRAINT IF EXISTS "atribuicoes_afiliados_link_origem_id_links_afiliados_id_fk";
ALTER TABLE "atribuicoes_afiliados" DROP CONSTRAINT IF EXISTS "atribuicoes_afiliados_parceiro_id_parceiros_afiliados_id_fk";
ALTER TABLE "atribuicoes_afiliados" DROP CONSTRAINT IF EXISTS "atribuicoes_afiliados_usuario_id_usuarios_id_fk";
ALTER TABLE "alocacoes_repasses" DROP CONSTRAINT IF EXISTS "alocacoes_repasses_liberacao_id_liberacoes_repasses_id_fk";
ALTER TABLE "alocacoes_repasses" DROP CONSTRAINT IF EXISTS "alocacoes_repasses_repasse_id_repasses_afiliados_id_fk";
ALTER TABLE "acordos_afiliados" DROP CONSTRAINT IF EXISTS "acordos_afiliados_criado_por_id_usuarios_id_fk";
ALTER TABLE "acordos_afiliados" DROP CONSTRAINT IF EXISTS "acordos_afiliados_oferta_id_ofertas_afiliados_id_fk";
ALTER TABLE "acordos_afiliados" DROP CONSTRAINT IF EXISTS "acordos_afiliados_parceiro_id_parceiros_afiliados_id_fk";
DROP TABLE IF EXISTS "repasses_afiliados" CASCADE;
DROP TABLE IF EXISTS "recebimentos_casas" CASCADE;
DROP TABLE IF EXISTS "parceiros_afiliados" CASCADE;
DROP TABLE IF EXISTS "ofertas_afiliados" CASCADE;
DROP TABLE IF EXISTS "lotes_importacao_afiliados" CASCADE;
DROP TABLE IF EXISTS "links_afiliados" CASCADE;
DROP TABLE IF EXISTS "liberacoes_repasses" CASCADE;
DROP TABLE IF EXISTS "itens_importacao_afiliados" CASCADE;
DROP TABLE IF EXISTS "eventos_afiliados" CASCADE;
DROP TABLE IF EXISTS "convites_afiliados" CASCADE;
DROP TABLE IF EXISTS "comissoes_afiliados" CASCADE;
DROP TABLE IF EXISTS "campanhas_afiliados" CASCADE;
DROP TABLE IF EXISTS "auditoria_afiliados" CASCADE;
DROP TABLE IF EXISTS "atribuicoes_afiliados" CASCADE;
DROP TABLE IF EXISTS "alocacoes_repasses" CASCADE;
DROP TABLE IF EXISTS "acordos_afiliados" CASCADE;
