export { CardEntrada, type CardEntradaProps } from './CardEntrada'
export { Anel, type AnelProps } from './Anel'
export { Selo, type SeloProps } from './Selo'
export { Historico, type HistoricoProps } from './Historico'
export { UltimaAtualizacao, type UltimaAtualizacaoProps } from './UltimaAtualizacao'
export { Tabela, type TabelaProps, type Coluna } from './Tabela'
export { Avatar, iniciaisDe, fundoDoTime } from './Avatar'
export { Pilula } from './Pilula'
