export { CardEntrada, type CardEntradaProps } from './CardEntrada'
export { Selo, type SeloProps } from './Selo'
export { Barrinhas, type BarrinhasProps } from './Barrinhas'
export { BarraAlvo, type BarraAlvoProps } from './BarraAlvo'
export { PlacarMini, type PlacarMiniProps } from './PlacarMini'
export { UltimaAtualizacao, type UltimaAtualizacaoProps } from './UltimaAtualizacao'
export { Tabela, type TabelaProps, type Coluna } from './Tabela'
export { Avatar, iniciaisDe, fundoDoTime } from './Avatar'
export { Pilula } from './Pilula'
