export { CardEntrada, type CardEntradaProps } from './CardEntrada'
export { Selo, type SeloProps } from './Selo'
export { Barrinhas, type BarrinhasProps } from './Barrinhas'
export { BarraAlvo, type BarraAlvoProps, type MarcoDaBarra } from './BarraAlvo'
export { PlacarMini, type PlacarMiniProps } from './PlacarMini'
export { UltimaAtualizacao, type UltimaAtualizacaoProps } from './UltimaAtualizacao'
export { Tabela, type TabelaProps, type Coluna } from './Tabela'
export { Avatar, iniciaisDe, fundoDoTime } from './Avatar'
export { Pilula } from './Pilula'
export { NotaPartida, type NotaPartidaProps } from './NotaPartida'
export { CabecalhoJogo, type CabecalhoJogoProps } from './CabecalhoJogo'
export { SeloContexto, type SeloContextoProps } from './SeloContexto'
export { FormaNoAtributo, type FormaNoAtributoProps, type JogoNaForma } from './FormaNoAtributo'
